// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for linux.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClhSx1mA0iwdw6DQmFd3Diz8IJwie3Lhk',
    appId: '1:451246976546:web:a8697b08e03fe5a0ed247b',
    messagingSenderId: '451246976546',
    projectId: 'seretei8',
    authDomain: 'seretei8.firebaseapp.com',
    storageBucket: 'seretei8.firebasestorage.app',
  );

  // ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjHAurQBhbY3gEfqV19v7lcdoqM08dkUU',
    appId: '1:451246976546:android:bb073ccbf2529104ed247b',
    messagingSenderId: '451246976546',
    projectId: 'seretei8',
    storageBucket: 'seretei8.firebasestorage.app',
  );

  // IOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9euc9kbRe3FXQBBhPLTQ41TkrBNig9c',
    appId: '1:451246976546:ios:6f57b39e43d5815eed247b',
    messagingSenderId: '451246976546',
    projectId: 'seretei8',
    storageBucket: 'seretei8.firebasestorage.app',
    iosBundleId: 'com.example.motoguard',
  );

  // MACOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa9euc9kbRe3FXQBBhPLTQ41TkrBNig9c',
    appId: '1:451246976546:ios:6f57b39e43d5815eed247b',
    messagingSenderId: '451246976546',
    projectId: 'seretei8',
    storageBucket: 'seretei8.firebasestorage.app',
    iosBundleId: 'com.example.motoguard',
  );

  // WINDOWS
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClhSx1mA0iwdw6DQmFd3Diz8IJwie3Lhk',
    appId: '1:451246976546:web:dc15b8f80a309698ed247b',
    messagingSenderId: '451246976546',
    projectId: 'seretei8',
    authDomain: 'seretei8.firebaseapp.com',
    storageBucket: 'seretei8.firebasestorage.app',
  );
}
