// Manual version of the file normally generated by `flutterfire configure`.
// Put it at:  lib/firebase_options.dart

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run: flutterfire configure --project=seretei8',
        );
    }
  }

  // Values taken from your Firebase web config (complete).
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClhSx1mA0iwdw6DQmFd3Diz8IJwie3Lhk',
    appId: '1:451246976546:web:a8697b08e03fe5a0ed247b',
    messagingSenderId: '451246976546',
    projectId: 'seretei8',
    authDomain: 'seretei8.firebaseapp.com',
    databaseURL:
        'https://seretei8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seretei8.firebasestorage.app',
  );

  // ANDROID: copy these 2 values from android/app/google-services.json
  //   apiKey -> "current_key"        (under api_key)
  //   appId  -> "mobilesdk_app_id"   (under client_info), looks like 1:451246976546:android:xxxxxxxx
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PASTE_current_key_FROM_google-services.json',
    appId: 'PASTE_mobilesdk_app_id_FROM_google-services.json',
    messagingSenderId: '451246976546',
    projectId: 'seretei8',
    databaseURL:
        'https://seretei8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seretei8.firebasestorage.app',
  );
}
