import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:firebase_core/firebase_core.dart';

// Generated by:  flutterfire configure --project=seretei8
// It must exist at lib/firebase_options.dart and define DefaultFirebaseOptions.
import 'firebase_options.dart';

import 'start.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ================= LOCK PORTRAIT =================
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);

  // ================= FIREBASE INIT =================
  await _initializeFirebase();

  runApp(const MyApp());
}

/// ================= FIREBASE INIT FUNCTION =================
Future<void> _initializeFirebase() async {
  try {
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      debugPrint('✅ Firebase initialized successfully');
    }
  } catch (e) {
    debugPrint('❌ Firebase initialization error: $e');
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MotoGuard',
      debugShowCheckedModeBanner: false,

      // ================= THEME =================
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF050709),
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.orange,
          brightness: Brightness.dark,
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF0F1318),
          elevation: 0,
          centerTitle: true,
          iconTheme: IconThemeData(
            color: Colors.orange,
          ),
          titleTextStyle: TextStyle(
            color: Colors.white,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),

      // ================= ALWAYS START PAGE FIRST =================
      home: const StartPage(),
    );
  }
}
