import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/material.dart';

import 'motor_verification.dart';

// ======================================================================
// CONFIGURATION
// ======================================================================

const String kMotorDevicesCollection = 'iotDevices';
const String kDefaultDeviceName = 'MotoGuard Device';

const String kMotoRtdbUrl =
    'https://seretei8-default-rtdb.asia-southeast1.firebasedatabase.app';

const int kHeartbeatTimeoutMs = 8000;
const int kClockToleranceMs = 10000;
const int kReattachEveryMs = 10000;

// ======================================================================
// HELPERS
// ======================================================================

int? _toInt(Object? value) {
  if (value is int) {
    return value;
  }

  if (value is num) {
    return value.toInt();
  }

  if (value is String) {
    return int.tryParse(value.trim());
  }

  return null;
}

double? _toDouble(Object? value) {
  if (value is num) {
    final d = value.toDouble();

    return d.isFinite ? d : null;
  }

  if (value is String) {
    final d = double.tryParse(value.trim());

    if (d != null && d.isFinite) {
      return d;
    }
  }

  return null;
}

bool _toBool(Object? value) {
  if (value is bool) {
    return value;
  }

  if (value is String) {
    return value.trim().toLowerCase() == 'true';
  }

  if (value is num) {
    return value != 0;
  }

  return false;
}

// ======================================================================
// MODEL
// ======================================================================

class MotoDevice {
  final String id;
  final String name;
  final Map<String, dynamic> data;

  const MotoDevice({
    required this.id,
    required this.name,
    required this.data,
  });

  factory MotoDevice.fromDoc(
    QueryDocumentSnapshot<Map<String, dynamic>> doc,
  ) {
    final data = doc.data();

    final rawName = data['name']?.toString().trim();
    final rawDeviceId = data['deviceId']?.toString().trim();

    final deviceId =
        rawDeviceId != null && rawDeviceId.isNotEmpty ? rawDeviceId : doc.id;

    return MotoDevice(
      id: deviceId,
      name:
          rawName != null && rawName.isNotEmpty ? rawName : kDefaultDeviceName,
      data: data,
    );
  }
}

// ======================================================================
// STATE
// ======================================================================

class MotoDeviceState {
  final bool loading;
  final String? error;
  final MotoDevice? device;

  const MotoDeviceState({
    this.loading = true,
    this.error,
    this.device,
  });
}

// ======================================================================
// ESP STATUS
// ======================================================================

enum EspLink {
  idle,
  connecting,
  connected,
  reconnecting,
  disconnected,
}

class EspStatus {
  final EspLink link;

  /// Firebase server timestamp.
  final int? lastUpdateMs;

  /// Timestamp generated by the ESP32/device.
  final int? deviceTimestamp;

  final int? satellites;

  final double? speedKmh;

  final double? latitude;
  final double? longitude;

  final double? altitude;
  final double? accuracy;
  final double? hdop;

  final String? status;

  final bool gpsFix;

  const EspStatus({
    this.link = EspLink.idle,
    this.lastUpdateMs,
    this.deviceTimestamp,
    this.satellites,
    this.speedKmh,
    this.latitude,
    this.longitude,
    this.altitude,
    this.accuracy,
    this.hdop,
    this.status,
    this.gpsFix = false,
  });
}

// ======================================================================
// SHARED DEVICE REGISTRY
// ======================================================================

class MotoDeviceRegistry {
  MotoDeviceRegistry._();

  static final MotoDeviceRegistry instance = MotoDeviceRegistry._();

  final ValueNotifier<MotoDeviceState> state = ValueNotifier<MotoDeviceState>(
    const MotoDeviceState(),
  );

  final ValueNotifier<EspStatus> esp = ValueNotifier<EspStatus>(
    const EspStatus(),
  );

  int _users = 0;

  StreamSubscription<User?>? _authSub;

  StreamSubscription<QuerySnapshot<Map<String, dynamic>>>? _deviceSub;

  // ====================================================================
  // RTDB
  // ====================================================================

  FirebaseDatabase? _rtdb;

  FirebaseDatabase get _db {
    return _rtdb ??= FirebaseDatabase.instanceFor(
      app: Firebase.app(),
      databaseURL: kMotoRtdbUrl,
    );
  }

  StreamSubscription<DatabaseEvent>? _hbSub;

  StreamSubscription<DatabaseEvent>? _offsetSub;

  Timer? _hbTimer;

  String? _hbDeviceId;

  bool _everSeen = false;

  int _offsetMs = 0;

  final Stopwatch _clock = Stopwatch()..start();

  int _startedMs = 0;

  int _lastChangeMs = 0;

  int _lastReattachMs = 0;

  int? _lastSeq;

  int? _lastUpdatedAt;

  int? _satellites;

  double? _speed;

  bool _gpsFix = false;

  // ====================================================================
  // RETAIN
  // ====================================================================

  void retain() {
    _users++;

    if (_users != 1) {
      return;
    }

    _offsetSub = _db.ref('.info/serverTimeOffset').onValue.listen(
      (event) {
        final value = event.snapshot.value;

        if (value is num) {
          _offsetMs = value.toInt();
        }
      },
      onError: (_) {},
    );

    _authSub = FirebaseAuth.instance.authStateChanges().listen(
          _bind,
        );
  }

  // ====================================================================
  // RELEASE
  // ====================================================================

  void release() {
    if (_users > 0) {
      _users--;
    }

    if (_users != 0) {
      return;
    }

    _authSub?.cancel();
    _authSub = null;

    _deviceSub?.cancel();
    _deviceSub = null;

    _offsetSub?.cancel();
    _offsetSub = null;

    _stopHeartbeat();

    state.value = const MotoDeviceState(
      loading: false,
    );
  }

  // ====================================================================
  // BIND CURRENT USER
  // ====================================================================

  void _bind(User? user) {
    _deviceSub?.cancel();
    _deviceSub = null;

    _stopHeartbeat();

    if (user == null) {
      state.value = const MotoDeviceState(
        loading: false,
      );

      return;
    }

    state.value = const MotoDeviceState();

    // ================================================================
    // Only listen to devices belonging to the current user.
    // ================================================================

    _deviceSub = FirebaseFirestore.instance
        .collection(kMotorDevicesCollection)
        .where(
          'connectedUserId',
          isEqualTo: user.uid,
        )
        .limit(1)
        .snapshots()
        .listen(
      (snapshot) {
        final device = snapshot.docs.isEmpty
            ? null
            : MotoDevice.fromDoc(
                snapshot.docs.first,
              );

        state.value = MotoDeviceState(
          loading: false,
          device: device,
        );

        if (device == null) {
          _stopHeartbeat();
        } else {
          _startHeartbeat(device.id);
        }
      },
      onError: (_) {
        state.value = MotoDeviceState(
          loading: false,
          error: 'Unable to load your device.',
          device: state.value.device,
        );
      },
    );
  }

  // ====================================================================
  // LIVE ESP32 HEARTBEAT
  // ====================================================================

  void _startHeartbeat(
    String deviceId,
  ) {
    if (_hbDeviceId == deviceId && _hbSub != null) {
      return;
    }

    _stopHeartbeat();

    _hbDeviceId = deviceId;

    _everSeen = false;

    _startedMs = _clock.elapsedMilliseconds;

    _lastChangeMs = _startedMs;

    _lastReattachMs = _startedMs;

    esp.value = const EspStatus(
      link: EspLink.connecting,
    );

    _attachHeartbeat();

    _hbTimer = Timer.periodic(
      const Duration(seconds: 1),
      (_) => _evaluateHeartbeat(),
    );
  }

  // ====================================================================
  // ATTACH RTDB LISTENER
  // ====================================================================

  void _attachHeartbeat() {
    final id = _hbDeviceId;

    if (id == null) {
      return;
    }

    _hbSub?.cancel();

    _hbSub = _db.ref('gps/$id').onValue.listen(
          _onHeartbeat,
          onError: (_) {},
        );
  }

  // ====================================================================
  // RECEIVE RTDB DATA
  // ====================================================================

  void _onHeartbeat(
    DatabaseEvent event,
  ) {
    final value = event.snapshot.value;

    if (value is! Map) {
      return;
    }

    // ---------------------------------------------------------------
    // Heartbeat fields
    // ---------------------------------------------------------------

    final updatedAt = _toInt(
      value['updatedAt'],
    );

    final seq = _toInt(
      value['seq'],
    );

    if (updatedAt != _lastUpdatedAt || seq != _lastSeq) {
      _lastUpdatedAt = updatedAt;
      _lastSeq = seq;

      _lastChangeMs = _clock.elapsedMilliseconds;
    }

    // ---------------------------------------------------------------
    // GPS fields
    // ---------------------------------------------------------------

    final satellites = _toInt(
      value['satellites'],
    );

    final speed = _toDouble(
      value['speed'],
    );

    final latitude = _toDouble(
      value['latitude'],
    );

    final longitude = _toDouble(
      value['longitude'],
    );

    final altitude = _toDouble(
      value['altitude'],
    );

    final accuracy = _toDouble(
      value['accuracy'],
    );

    final hdop = _toDouble(
      value['hdop'],
    );

    final deviceTimestamp = _toInt(
      value['deviceTimestamp'],
    );

    final gpsFix = _toBool(
      value['gpsFix'],
    );

    final gpsStatus = value['status']?.toString();

    // ---------------------------------------------------------------
    // Cache basic heartbeat values
    // ---------------------------------------------------------------

    _satellites = satellites;

    _speed = speed;

    _gpsFix = gpsFix;

    // ---------------------------------------------------------------
    // Evaluate connection state.
    //
    // This updates the EspStatus and preserves the GPS fields.
    // ---------------------------------------------------------------

    _evaluateHeartbeat(
      latitude: latitude,
      longitude: longitude,
      altitude: altitude,
      accuracy: accuracy,
      hdop: hdop,
      deviceTimestamp: deviceTimestamp,
      gpsStatus: gpsStatus,
    );
  }

  // ====================================================================
  // HEARTBEAT EVALUATION
  // ====================================================================

  void _evaluateHeartbeat({
    double? latitude,
    double? longitude,
    double? altitude,
    double? accuracy,
    double? hdop,
    int? deviceTimestamp,
    String? gpsStatus,
  }) {
    if (_hbDeviceId == null) {
      return;
    }

    final now = _clock.elapsedMilliseconds;

    final silence = now - _lastChangeMs;

    final updatedAt = _lastUpdatedAt;

    final serverNow = DateTime.now().millisecondsSinceEpoch + _offsetMs;

    final age = updatedAt == null ? null : serverNow - updatedAt;

    final alive = age != null &&
        age <= kHeartbeatTimeoutMs &&
        age >= -kClockToleranceMs &&
        silence <= kHeartbeatTimeoutMs;

    EspLink link;

    if (alive) {
      _everSeen = true;

      link = EspLink.connected;
    } else if (_everSeen) {
      link = EspLink.reconnecting;
    } else if (updatedAt == null && now - _startedMs < 6000) {
      link = EspLink.connecting;
    } else {
      link = EspLink.disconnected;
    }

    // ================================================================
    // AUTO RECONNECT
    // ================================================================

    if (!alive && now - _lastReattachMs >= kReattachEveryMs) {
      _lastReattachMs = now;

      _db.goOnline();

      _attachHeartbeat();
    }

    // ================================================================
    // Preserve existing GPS data if this call is only a heartbeat
    // evaluation.
    // ================================================================

    final current = esp.value;

    esp.value = EspStatus(
      link: link,
      lastUpdateMs: updatedAt,
      deviceTimestamp: deviceTimestamp ?? current.deviceTimestamp,
      satellites: _satellites,
      speedKmh: _speed,
      latitude: latitude ?? current.latitude,
      longitude: longitude ?? current.longitude,
      altitude: altitude ?? current.altitude,
      accuracy: accuracy ?? current.accuracy,
      hdop: hdop ?? current.hdop,
      status: gpsStatus ?? current.status,
      gpsFix: _gpsFix,
    );
  }

  // ====================================================================
  // STOP HEARTBEAT
  // ====================================================================

  void _stopHeartbeat() {
    _hbTimer?.cancel();

    _hbTimer = null;

    _hbSub?.cancel();

    _hbSub = null;

    _hbDeviceId = null;

    _everSeen = false;

    _lastSeq = null;

    _lastUpdatedAt = null;

    _satellites = null;

    _speed = null;

    _gpsFix = false;

    if (esp.value.link != EspLink.idle) {
      esp.value = const EspStatus();
    }
  }

  // ====================================================================
  // REMOVE DEVICE
  //
  // NO CLOUD FUNCTIONS.
  //
  // Firestore Rules verify that the current user owns the device.
  // ====================================================================

  Future<void> removeDevice(
    String deviceId,
  ) async {
    final user = FirebaseAuth.instance.currentUser;

    if (user == null) {
      throw FirebaseException(
        plugin: 'firebase_auth',
        code: 'unauthenticated',
        message: 'Please login first.',
      );
    }

    final ref = FirebaseFirestore.instance
        .collection(kMotorDevicesCollection)
        .doc(deviceId);

    await ref.update({
      'status': 'available',
      'connectedUserId': '',
      'connectedAt': FieldValue.delete(),
    });
  }
}

// ======================================================================
// PAGE
// ======================================================================

class MyDevicePage extends StatefulWidget {
  const MyDevicePage({
    super.key,
  });

  @override
  State<MyDevicePage> createState() => _MyDevicePageState();
}

class _MyDevicePageState extends State<MyDevicePage> {
  static const Color cyberGreen = Color(0xFF00E676);

  static const Color darkGreen = Color(0xFF071A12);

  final MotoDeviceRegistry _registry = MotoDeviceRegistry.instance;

  bool _busy = false;

  @override
  void initState() {
    super.initState();

    _registry.retain();
  }

  @override
  void dispose() {
    _registry.release();

    super.dispose();
  }

  // ====================================================================
  // ADD DEVICE
  // ====================================================================

  Future<void> addDevice() async {
    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => const MotorVerificationPage(),
      ),
    );
  }

  // ====================================================================
  // REMOVE DEVICE
  // ====================================================================

  Future<void> removeDevice(
    MotoDevice device,
  ) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (dialogContext) {
        return AlertDialog(
          backgroundColor: const Color(0xFF0A1711),
          title: const Text(
            'Remove Device?',
            style: TextStyle(
              color: Colors.white,
            ),
          ),
          content: const Text(
            'This will remove the motorcycle '
            'from your account. The device can '
            'then be registered by another account.',
            style: TextStyle(
              color: Colors.white70,
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(
                dialogContext,
                false,
              ),
              child: const Text(
                'CANCEL',
                style: TextStyle(
                  color: Colors.white54,
                ),
              ),
            ),
            TextButton(
              onPressed: () => Navigator.pop(
                dialogContext,
                true,
              ),
              child: const Text(
                'REMOVE',
                style: TextStyle(
                  color: Colors.redAccent,
                ),
              ),
            ),
          ],
        );
      },
    );

    if (confirmed != true || !mounted) {
      return;
    }

    setState(() {
      _busy = true;
    });

    try {
      await _registry.removeDevice(
        device.id,
      );

      if (!mounted) {
        return;
      }

      setState(() {
        _busy = false;
      });

      showMessage(
        'Device removed successfully.',
      );
    } on FirebaseException catch (e) {
      if (!mounted) {
        return;
      }

      setState(() {
        _busy = false;
      });

      if (e.code == 'permission-denied') {
        showMessage(
          'You are not allowed to remove this device.',
        );
      } else if (e.code == 'not-found') {
        showMessage(
          'Device was not found.',
        );
      } else {
        showMessage(
          e.message ?? 'Unable to remove device.',
        );
      }
    } catch (_) {
      if (!mounted) {
        return;
      }

      setState(() {
        _busy = false;
      });

      showMessage(
        'Unable to remove device.',
      );
    }
  }

  // ====================================================================
  // MESSAGE
  // ====================================================================

  void showMessage(
    String message,
  ) {
    if (!mounted) {
      return;
    }

    final messenger = ScaffoldMessenger.of(context);

    messenger.hideCurrentSnackBar();

    messenger.showSnackBar(
      SnackBar(
        content: Text(
          message,
          style: const TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w600,
          ),
        ),
        backgroundColor: const Color(0xFF08110D),
        behavior: SnackBarBehavior.floating,
        margin: const EdgeInsets.all(16),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(14),
        ),
      ),
    );
  }

  // ====================================================================
  // CLOCK
  // ====================================================================

  String _fmtClock(
    int? ms,
  ) {
    if (ms == null) {
      return '--:--:--';
    }

    final d = DateTime.fromMillisecondsSinceEpoch(
      ms,
    ).toLocal();

    String two(int n) => n.toString().padLeft(2, '0');

    return '${two(d.hour)}:'
        '${two(d.minute)}:'
        '${two(d.second)}';
  }

  // ====================================================================
  // BUILD
  // ====================================================================

  @override
  Widget build(
    BuildContext context,
  ) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        foregroundColor: Colors.white,
        elevation: 0,
        title: const Text(
          'My Device',
          style: TextStyle(
            fontWeight: FontWeight.w800,
          ),
        ),
      ),
      body: ValueListenableBuilder<MotoDeviceState>(
        valueListenable: _registry.state,
        builder: (
          context,
          state,
          _,
        ) {
          if (state.loading || _busy) {
            return const Center(
              child: CircularProgressIndicator(
                color: cyberGreen,
              ),
            );
          }

          final device = state.device;

          return SingleChildScrollView(
            padding: const EdgeInsets.all(20),
            child: device != null
                ? _buildConnectedDevice(
                    device,
                  )
                : state.error != null
                    ? _buildError(
                        state.error!,
                      )
                    : _buildNoDevice(),
          );
        },
      ),
    );
  }

  // ====================================================================
  // ERROR
  // ====================================================================

  Widget _buildError(
    String message,
  ) {
    return Padding(
      padding: const EdgeInsets.only(
        top: 80,
      ),
      child: Center(
        child: Text(
          message,
          textAlign: TextAlign.center,
          style: const TextStyle(
            color: Colors.redAccent,
            fontSize: 15,
          ),
        ),
      ),
    );
  }

  // ====================================================================
  // NO DEVICE
  // ====================================================================

  Widget _buildNoDevice() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(28),
      decoration: BoxDecoration(
        color: darkGreen,
        borderRadius: BorderRadius.circular(28),
        border: Border.all(
          color: cyberGreen.withValues(
            alpha: 0.15,
          ),
        ),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const Icon(
            Icons.two_wheeler_rounded,
            size: 70,
            color: cyberGreen,
          ),
          const SizedBox(
            height: 20,
          ),
          const Text(
            'No Device Connected',
            style: TextStyle(
              color: Colors.white,
              fontSize: 22,
              fontWeight: FontWeight.w800,
            ),
          ),
          const SizedBox(
            height: 10,
          ),
          const Text(
            'Connect your MotoGuard '
            'motorcycle using its '
            'device ID and passkey.',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Colors.white54,
              fontSize: 14,
            ),
          ),
          const SizedBox(
            height: 25,
          ),
          SizedBox(
            width: double.infinity,
            height: 54,
            child: ElevatedButton.icon(
              onPressed: addDevice,
              icon: const Icon(
                Icons.add_link_rounded,
              ),
              label: const Text(
                'ADD DEVICE',
                style: TextStyle(
                  fontWeight: FontWeight.w900,
                  letterSpacing: 1.2,
                ),
              ),
              style: ElevatedButton.styleFrom(
                backgroundColor: cyberGreen,
                foregroundColor: Colors.black,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(
                    16,
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  // ====================================================================
  // CONNECTED DEVICE
  // ====================================================================

  Widget _buildConnectedDevice(
    MotoDevice device,
  ) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          width: double.infinity,
          padding: const EdgeInsets.all(24),
          decoration: BoxDecoration(
            color: darkGreen,
            borderRadius: BorderRadius.circular(28),
            border: Border.all(
              color: cyberGreen.withValues(
                alpha: 0.2,
              ),
            ),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Icon(
                Icons.two_wheeler_rounded,
                size: 55,
                color: cyberGreen,
              ),
              const SizedBox(
                height: 18,
              ),
              Text(
                device.name,
                style: const TextStyle(
                  color: Colors.white,
                  fontSize: 24,
                  fontWeight: FontWeight.w900,
                ),
              ),
              const SizedBox(
                height: 8,
              ),
              Text(
                'Device ID: ${device.id}',
                style: const TextStyle(
                  color: Colors.white54,
                  fontSize: 13,
                ),
              ),
              const SizedBox(
                height: 18,
              ),
              ValueListenableBuilder<EspStatus>(
                valueListenable: _registry.esp,
                builder: (
                  context,
                  esp,
                  _,
                ) {
                  return _buildLiveStatus(
                    esp,
                  );
                },
              ),
            ],
          ),
        ),
        const SizedBox(
          height: 25,
        ),
        SizedBox(
          width: double.infinity,
          height: 54,
          child: OutlinedButton.icon(
            onPressed: _busy
                ? null
                : () => removeDevice(
                      device,
                    ),
            icon: const Icon(
              Icons.link_off_rounded,
              color: Colors.redAccent,
            ),
            label: const Text(
              'REMOVE DEVICE',
              style: TextStyle(
                color: Colors.redAccent,
                fontWeight: FontWeight.w800,
                letterSpacing: 1,
              ),
            ),
            style: OutlinedButton.styleFrom(
              side: const BorderSide(
                color: Colors.redAccent,
              ),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(
                  16,
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }

  // ====================================================================
  // LIVE STATUS
  // ====================================================================

  Widget _buildLiveStatus(
    EspStatus esp,
  ) {
    Color color;

    String label;

    switch (esp.link) {
      case EspLink.connected:
        color = cyberGreen;
        label = 'ESP32 CONNECTED';
        break;

      case EspLink.reconnecting:
        color = Colors.orangeAccent;
        label = 'ESP32 DISCONNECTED - RECONNECTING...';
        break;

      case EspLink.disconnected:
        color = Colors.redAccent;
        label = 'ESP32 OFFLINE - RETRYING...';
        break;

      case EspLink.connecting:
      case EspLink.idle:
        color = Colors.grey;
        label = 'CONNECTING TO ESP32...';
        break;
    }

    final connected = esp.link == EspLink.connected;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // ============================================================
        // CONNECTION STATUS
        // ============================================================

        Row(
          children: [
            Icon(
              Icons.circle,
              color: color,
              size: 10,
            ),
            const SizedBox(
              width: 8,
            ),
            Flexible(
              child: Text(
                label,
                style: TextStyle(
                  color: color,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 1,
                ),
              ),
            ),
          ],
        ),

        const SizedBox(
          height: 14,
        ),

        _infoRow(
          'Last update',
          _fmtClock(
            esp.lastUpdateMs,
          ),
        ),

        _infoRow(
          'GPS fix',
          connected
              ? esp.gpsFix
                  ? 'Yes'
                  : 'Searching...'
              : '--',
        ),

        _infoRow(
          'Satellites',
          connected ? esp.satellites?.toString() ?? '--' : '--',
        ),

        _infoRow(
          'Speed',
          connected && esp.speedKmh != null
              ? '${esp.speedKmh!.toStringAsFixed(1)} km/h'
              : '--',
        ),

        _infoRow(
          'Latitude',
          connected && esp.latitude != null
              ? esp.latitude!.toStringAsFixed(6)
              : '--',
        ),

        _infoRow(
          'Longitude',
          connected && esp.longitude != null
              ? esp.longitude!.toStringAsFixed(6)
              : '--',
        ),

        _infoRow(
          'Altitude',
          connected && esp.altitude != null
              ? '${esp.altitude!.toStringAsFixed(1)} m'
              : '--',
        ),

        _infoRow(
          'Accuracy',
          connected && esp.accuracy != null
              ? '${esp.accuracy!.toStringAsFixed(1)} m'
              : '--',
        ),

        _infoRow(
          'HDOP',
          connected && esp.hdop != null ? esp.hdop!.toStringAsFixed(1) : '--',
        ),

        _infoRow(
          'Status',
          connected && esp.status != null ? esp.status! : '--',
        ),

        _infoRow(
          'Device time',
          _fmtClock(
            esp.deviceTimestamp,
          ),
        ),
      ],
    );
  }

  // ====================================================================
  // INFO ROW
  // ====================================================================

  Widget _infoRow(
    String label,
    String value,
  ) {
    return Padding(
      padding: const EdgeInsets.symmetric(
        vertical: 2,
      ),
      child: Row(
        children: [
          SizedBox(
            width: 100,
            child: Text(
              '$label:',
              style: const TextStyle(
                color: Colors.white54,
                fontSize: 13,
              ),
            ),
          ),
          Expanded(
            child: Text(
              value,
              style: const TextStyle(
                color: Colors.white,
                fontSize: 13,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
